export const COACHES = [
  {
    id: "377706c2-d0a4-11ee-b135-19f9e53c40f5",
    name: "David",
    titledName: "Coach David",
    imageUrl: "https://assets-coaches.chess.com/image/coachdavid.png?v=41de5a5d",
    iconUrl: "https://assets-coaches.chess.com/image/coachdavid-icon.png?v=fd8652ae",
    voiceId: "David_coach",
    locale: "en-US",
    textId: "Generic_coach",
    riveAnimationUrl: "https://assets-coaches.chess.com/image/coach_david.riv?v=6ae35776",
    greetingRiveAnimationUrl: "https://assets-coaches.chess.com/image/coach_david_greeting.riv?v=5b1b0874",
    taglines: [
      "Hi, I'm Coach David. I'm here to teach you all about chess.",
      "Hi, I'm David. Choose me and I'll help you learn chess.",
      "Hi, Coach David here! I'm ready to share my chess knowledge with you.",
      "David is my name, coaching is my game. Choose me!",
      "Hey, I'm David. Will you be my student?",
    ],
  },
  {
    id: "167864ce-ab73-11f0-8bbc-45df3aeaea91",
    name: "Sloane",
    titledName: "Coach Sloane",
    imageUrl: "https://assets-coaches.chess.com/image/coachsloane.png?v=6c448cfa",
    iconUrl: "https://assets-coaches.chess.com/image/coachsloane-icon.png?v=0a4c5293",
    voiceId: "Sloane_coach",
    locale: "en-US",
    textId: "Sloane_coach",
    riveAnimationUrl: "https://assets-coaches.chess.com/image/coach_sloane.riv?v=c3e13fe7",
    greetingRiveAnimationUrl: "https://assets-coaches.chess.com/image/coach_sloane_greeting.riv?v=efa3d5ef",
    taglines: [
      "Hey, I'm Sloane. Choose me as your coach and I'll teach you everything I know.",
      "My chess vision is up there with the greats. Ready to see what I see?",
      "Want to build confidence while you learn? Pick me.",
      "I'm ready to guide you, move by move. Pick me and let's learn some chess.",
    ],
  },
  {
    id: "d628d4bc-a0f1-11ef-9a6c-59c0254292e3",
    name: "Magnus",
    titledName: "Coach Magnus",
    imageUrl: "https://assets-coaches.chess.com/image/coachmagnus.png?v=819d9dba",
    iconUrl: "https://assets-coaches.chess.com/image/coachmagnus-icon.png?v=9e82f767",
    voiceId: "Magnus_coach",
    locale: "en-US",
    textId: "Magnus_coach",
    riveAnimationUrl: "https://assets-coaches.chess.com/image/coach_magnus.riv?v=971e249f",
    greetingRiveAnimationUrl: "https://assets-coaches.chess.com/image/coach_magnus_greeting.riv?v=36611f00",
    taglines: [
      "Want to be coached by the highest rated chess player in history? Pick me.",
      "I was the World Champion for ten years, I'm the perfect chess coach for you.",
      "I mean, come on... you're going to choose me, right?",
      "Now's your chance to tell people Magnus Carlsen is your chess coach.",
    ],
  },
  {
    id: "6ddf1ca2-ff6c-11ef-baea-5dc78a000edb",
    name: "Levy",
    titledName: "Coach Levy",
    imageUrl: "https://assets-coaches.chess.com/image/coachlevy.png?v=9f98615d",
    iconUrl: "https://assets-coaches.chess.com/image/coachlevy-icon.png?v=19825017",
    voiceId: "Levy_coach",
    locale: "en-US",
    textId: "Levy_coach",
    riveAnimationUrl: "https://assets-coaches.chess.com/image/coach_levy.riv?v=21120709",
    greetingRiveAnimationUrl: "https://assets-coaches.chess.com/image/coach_levy_greeting.riv?v=38752839",
    taglines: [
      "GothamChess here! I'm the internet's chess teacher, who else could you possibly pick?",
      "Choose me as your coach and I'll make you a better chess player!",
      "I'm just a chill guy who can improve your chess game. Pick me!",
      "Levy Rozman reporting for duty. I'm the best possible choice here, no clickbait.",
    ],
  },
  {
    id: "1678e624-ab73-11f0-9644-6fc23344afd8",
    name: "Calvin",
    titledName: "Coach Calvin",
    imageUrl: "https://assets-coaches.chess.com/image/coachcalvin.png?v=2fa90df5",
    iconUrl: "https://assets-coaches.chess.com/image/coachcalvin-icon.png?v=730ed413",
    voiceId: "Calvin_coach",
    locale: "en-US",
    textId: "Calvin_coach",
    riveAnimationUrl: "",
    greetingRiveAnimationUrl: "",
    taglines: [
      "You need an expert chess coach? Say no more.",
      "I'm the best chess player in my school. Ready to learn?",
      "I'm the coach you want in your corner. Let's do this.",
      "Are we standing around or are we playing chess? C'mon!",
    ],
  },
  {
    id: "4fdf1a48-7917-11f0-83ed-d56e6dd5307c",
    name: "Anna",
    titledName: "Coach Anna",
    imageUrl: "https://assets-coaches.chess.com/image/coachanna.png?v=745c4e84",
    iconUrl: "https://assets-coaches.chess.com/image/coachanna-icon.png?v=ac97bcaa",
    voiceId: "Anna_coach",
    locale: "en-US",
    textId: "Anna_coach",
    riveAnimationUrl: "",
    greetingRiveAnimationUrl: "",
    taglines: [
      "Hi, I'm Anna! I love teaching chess and I'm here to help you improve.",
      "Let's learn some chess together. Pick me as your coach!",
    ],
  },
  {
    id: "d62aa12a-a0f1-11ef-8c86-0b794ad057db",
    name: "Tania",
    titledName: "Coach Tania",
    imageUrl: "https://assets-coaches.chess.com/image/coachtania.png?v=dc1e4f9f",
    iconUrl: "https://assets-coaches.chess.com/image/coachtania-icon.png?v=271636b6",
    voiceId: "Tania_coach",
    locale: "en-US",
    textId: "Tania_coach",
    riveAnimationUrl: "",
    greetingRiveAnimationUrl: "",
    taglines: [
      "I've commentated on the best in the world. Now I'm here to help you play like them!",
      "Want to learn chess from an Olympiad gold medalist? Pick me.",
      "Coach Tania here! I can help you become a better chess player!",
      "It's Tania. You're going to want to be my student. Trust me!",
    ],
  },
  {
    id: "6dd9d7b0-ff6c-11ef-9341-ff6621b6b8b5",
    name: "Danny",
    titledName: "Coach Danny",
    imageUrl: "https://assets-coaches.chess.com/image/coachdanny.png?v=7fd13701",
    iconUrl: "https://assets-coaches.chess.com/image/coachdanny-icon.png?v=2fc4419f",
    voiceId: "Danny_coach",
    locale: "en-US",
    textId: "Danny_coach",
    riveAnimationUrl: "",
    greetingRiveAnimationUrl: "",
    taglines: [
      "Want to learn from Chess.com's Chief Chess Officer?",
      "Have no fear, Coach Danny is here! I'll teach you everything you need to know.",
      "Nice job finding my avatar, now click the big green button. You're so close. You can do this.",
      "Improve your game with tips from me, a world-class chess commentator.",
    ],
  },
  {
    id: "d62a2aba-a0f1-11ef-a2f0-9118eb9f958d",
    name: "Botez",
    titledName: "Coach Botez",
    imageUrl: "https://assets-coaches.chess.com/image/coachbotezsisters.png?v=794138d4",
    iconUrl: "https://assets-coaches.chess.com/image/coachbotezsisters-icon.png?v=8824e754",
    voiceId: "Botez_coach",
    locale: "en-US",
    textId: "Botez_coach",
    riveAnimationUrl: "https://assets-coaches.chess.com/image/coach_botez.riv?v=ce5847dc",
    greetingRiveAnimationUrl: "https://assets-coaches.chess.com/image/coach_botez_greeting.riv?v=1c071485",
    taglines: [
      "Recognize us from YouTube? We'll make you a better chess player!",
      "Double trouble! We can help you achieve chess glory.",
      "Want TWO chess coaches instead of one? We're the right choice.",
      "Alexandra and Andrea here! You'd be a FOOL not to pick us!",
    ],
  },
  {
    id: "6dde8ddc-ff6c-11ef-a8d2-d5eb2eeec084",
    name: "Ben",
    titledName: "Coach Ben",
    imageUrl: "https://assets-coaches.chess.com/image/coachben.png?v=80369bf7",
    iconUrl: "https://assets-coaches.chess.com/image/coachben-icon.png?v=b27b2f23",
    voiceId: "Ben_coach",
    locale: "en-US",
    textId: "Ben_coach",
    riveAnimationUrl: "",
    greetingRiveAnimationUrl: "",
    taglines: [
      "Hey, it's Ben. You can pick me if you want, but I'll probably make fun of your blunders.",
      "If you pick me, you may learn a thing or two. I am a grandmaster after all.",
      "Trust me, you'll want me as your coach. The horsey goes diagonally, right?",
      "You're thinking about picking me? Think twice, bucko.",
    ],
  },
  {
    id: "d628d4bc-a0f1-11ef-9a6c-59c0254292e4",
    name: "Vishy",
    titledName: "Coach Vishy",
    imageUrl: "https://assets-coaches.chess.com/image/coachvishy.png?v=ea3d532d",
    iconUrl: "https://assets-coaches.chess.com/image/coachvishy-icon.png?v=9c622a35",
    voiceId: "Anand_coach",
    locale: "en-US",
    textId: "Anand_coach",
    riveAnimationUrl: "",
    greetingRiveAnimationUrl: "",
    taglines: [
      "I am Vishy Anand, the 5-time World Champion. Nice to meet you.",
      "Pick me to take your game to the next level.",
      "Let me help you get better at this lovely game! Take it from a World Champion.",
      "Vishy Anand, naam to suna hi hoga.",
    ],
  },
];

export const DEFAULT_COACH = COACHES[0];

export function findCoach(id) {
  return COACHES.find((c) => c.id === id) || null;
}

export function coachByVoiceId(voiceId) {
  return COACHES.find((c) => c.voiceId === voiceId) || null;
}
